-- Xóa bảng cũ
DROP TABLE EX_REACT_Customer;

-- Tạo lại bảng với điều kiện kiểm tra ID_NUMBER, PHONE, và EMAIL
CREATE TABLE EX_REACT_Customer (
    CUSTOMER_ID NUMBER DEFAULT customer_id_seq.NEXTVAL PRIMARY KEY,
    CUSTOMER_TYPE VARCHAR2(20) CHECK (CUSTOMER_TYPE IN ('Cá nhân', 'Tổ chức')) NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    REGISTRATION_DATE DATE NOT NULL,
    ID_NUMBER VARCHAR2(20) UNIQUE CHECK (LENGTH(ID_NUMBER) IN (9, 12)) NOT NULL,
    ADDRESS VARCHAR2(200) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE CHECK (REGEXP_LIKE(EMAIL, '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$')) NOT NULL,
    PHONE VARCHAR2(20) UNIQUE CHECK (LENGTH(PHONE) BETWEEN 10 AND 12) NOT NULL
);

-- Thêm dữ liệu mới với các giá trị phù hợp
INSERT INTO EX_REACT_Customer (CUSTOMER_ID, CUSTOMER_TYPE, NAME, REGISTRATION_DATE, ID_NUMBER, ADDRESS, EMAIL, PHONE) 
VALUES (customer_id_seq.NEXTVAL, 'Cá nhân', 'Nguyễn Văn A', TO_DATE('1990-01-01', 'YYYY-MM-DD'), '123456789', 'Đường ABC, Quận XYZ, TP HCM', 'nguyenvana@example.com', '0123456789');

INSERT INTO EX_REACT_Customer (CUSTOMER_ID, CUSTOMER_TYPE, NAME, REGISTRATION_DATE, ID_NUMBER, ADDRESS, EMAIL, PHONE) 
VALUES (customer_id_seq.NEXTVAL, 'Tổ chức', 'Công ty ABC', TO_DATE('2000-05-15', 'YYYY-MM-DD'), '123456789012', 'Đường XYZ, Quận ABC, TP Hà Nội', 'congtyabc@example.com', '0987654321');

INSERT INTO EX_REACT_Customer (CUSTOMER_ID, CUSTOMER_TYPE, NAME, REGISTRATION_DATE, ID_NUMBER, ADDRESS, EMAIL, PHONE) 
VALUES (customer_id_seq.NEXTVAL, 'Cá nhân', 'Trần Thị B', TO_DATE('1985-07-10', 'YYYY-MM-DD'), '987654321', 'Đường XYZ, Quận ABC, TP Hà Nội', 'tranthib@example.com', '0369852147');

INSERT INTO EX_REACT_Customer (CUSTOMER_ID, CUSTOMER_TYPE, NAME, REGISTRATION_DATE, ID_NUMBER, ADDRESS, EMAIL, PHONE) 
VALUES (customer_id_seq.NEXTVAL, 'Tổ chức', 'Công ty XYZ', TO_DATE('2010-10-20', 'YYYY-MM-DD'), '789012345678', 'Đường UVW, Quận DEF, TP Hồ Chí Minh', 'congtyxyz@example.com', '012345678910');

INSERT INTO EX_REACT_Customer (CUSTOMER_ID, CUSTOMER_TYPE, NAME, REGISTRATION_DATE, ID_NUMBER, ADDRESS, EMAIL, PHONE) 
VALUES (customer_id_seq.NEXTVAL, 'Cá nhân', 'Lê Văn C', TO_DATE('1988-03-25', 'YYYY-MM-DD'), '456789012', 'Đường MNO, Quận GHI, TP Hà Nội', 'levanc@example.com', '098765432109');
--value không phù hợp
INSERT INTO EX_REACT_Customer (CUSTOMER_ID, CUSTOMER_TYPE, NAME, REGISTRATION_DATE, ID_NUMBER, ADDRESS, EMAIL, PHONE) 
VALUES (customer_id_seq.NEXTVAL, 'Cá nhân', 'Nguyễn Văn A', TO_DATE('1990-01-01', 'YYYY-MM-DD'), '123', 'Đường ABC, Quận XYZ, TP HCM', 'nguyenvana@example.com', '123456789');

INSERT INTO EX_REACT_Customer (CUSTOMER_ID, CUSTOMER_TYPE, NAME, REGISTRATION_DATE, ID_NUMBER, ADDRESS, EMAIL, PHONE) 
VALUES (customer_id_seq.NEXTVAL, 'Tổ chức', 'Công ty ABC', TO_DATE('2000-05-15', 'YYYY-MM-DD'), '1234567890123', 'Đường XYZ, Quận ABC, TP Hà Nội', 'congtyabc@example', '09876543211234');

SELECT * FROM EX_REACT_Customer;

COMMIT;

